services:
  app:
    image: ghcr.io/basementcat/fruitstand:master
    command: [
      '--processes=4',
      '--py-autoreload=1',
      '--http-socket=0.0.0.0:3031'
    ]
    ports:
      - 3031:3031
    restart: always
    depends_on:
      - db
    environment:
      - FRUITSTAND_SECRET_KEY=lkasdjfalsdkjflskjdklsjdflk
      - FRUITSTAND_SQLALCHEMY_DATABASE_URI=mysql+pymysql://fruitstand:password@db:3306/fruitstand
      - FRUITSTAND_CACHE_DRIVER=database
      - FRUITSTAND_INTERNAL_WEB_HOST=web

  db:
    image: mariadb:lts
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=fruitstand
      - MARIADB_USER=fruitstand
      - MARIADB_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
