"""Initial migration

Revision ID: a47cf24d4881
Revises: 
Create Date: 2025-07-14 20:38:34.436651

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a47cf24d4881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('default_refresh_interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screen',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('key', sa.Unicode(length=64), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('playlist_screen',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('playlist_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('screen_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_pls_playlist', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name='fk_pls_screen', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('screen_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=True),
    sa.Column('playlist_screen_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=True),
    sa.Column('key', sa.Unicode(length=64), nullable=False),
    sa.Column('value_serialized', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_screen_id'], ['playlist_screen.id'], name='fk_config_playlist_screen', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name='fk_config_screen', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('display',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('key', sa.Unicode(length=64), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('last_seen_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('display_spec', sa.String(length=255), nullable=False),
    sa.Column('color_spec', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=True),
    sa.Column('last_playlist_screen_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=True),
    sa.ForeignKeyConstraint(['last_playlist_screen_id'], ['playlist_screen.id'], name='fk_display_last_pls_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_display_playlist', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('display')
    op.drop_table('config')
    op.drop_table('playlist_screen')
    op.drop_table('screen')
    op.drop_table('playlist')
    # ### end Alembic commands ###
