"""screen approval

Revision ID: 96501d4a76c9
Revises: e3d3eae9a7c3
Create Date: 2026-01-07 03:19:31.642935

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '96501d4a76c9'
down_revision = 'e3d3eae9a7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Unicode(length=255), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('approval_code', sa.Unicode(length=36), nullable=True))

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('system')

    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.drop_column('approval_code')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
