"""Remove system screens

Revision ID: 31419001fc07
Revises: 84a28e9fdbb7
Create Date: 2026-01-28 13:43:21.909674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '31419001fc07'
down_revision = '84a28e9fdbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from screen where `key` in ('fruitstand/approval_code', 'fruitstand/error');")
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('system')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # On downgrade, screens are correctly updated on next sync
    # ### end Alembic commands ###
