"""display auth

Revision ID: 6bda9090d0d3
Revises: 96501d4a76c9
Create Date: 2026-01-08 15:55:36.657920

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6bda9090d0d3'
down_revision = '96501d4a76c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_secret',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=255), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_secret_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=True))
        batch_op.create_foreign_key('fk_display_display_secret_id', 'display_secret', ['display_secret_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.drop_constraint('fk_display_display_secret_id', type_='foreignkey')
        batch_op.drop_column('display_secret_id')

    op.drop_table('display_secret')
    # ### end Alembic commands ###
