"""image format

Revision ID: 84a28e9fdbb7
Revises: 6bda9090d0d3
Create Date: 2026-01-23 14:14:40.125158

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '84a28e9fdbb7'
down_revision = '6bda9090d0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_format', sa.String(length=8), server_default='BMP', nullable=False))
        batch_op.add_column(sa.Column('image_bit_depth', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.drop_column('image_bit_depth')
        batch_op.drop_column('image_format')

    # ### end Alembic commands ###
