"""users

Revision ID: e3d3eae9a7c3
Revises: 53761cfc7c6f
Create Date: 2026-01-06 12:28:47.531682

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e3d3eae9a7c3'
down_revision = '53761cfc7c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('username_slug', sa.Unicode(length=128), nullable=False),
    sa.Column('email', sa.Unicode(length=256), nullable=False),
    sa.Column('raw_password', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
